In [16]:
import os
import pandas as pd
import sys
# not great because assumes this is run from the location of the notebook, but no easy workaround
parent_dir = os.path.abspath(os.path.join(os.getcwd(), ".."))
if parent_dir not in sys.path:
    sys.path.append(parent_dir)

from data import make_features, load_and_clean_aapl_stock_data

In [17]:
def get_data_with_features():
    data = load_and_clean_aapl_stock_data("../data/HistoricalQuotes.csv")
    data.rename({"Close": "AAPL Close"}, axis="columns", inplace=True)
    print("Columns of data after selecting Close and renaming it:", data.columns)
    
    data, feature_names = make_features(data)
    print("Columns of data after make_features:", data.columns)
    print("feature_names =", feature_names)
    
    return data, feature_names

In [18]:
data, feature_names = get_data_with_features()
data

Data size: (2518, 6); #NaNs = 0
Columns of data after selecting Close and renaming it: Index(['AAPL Close'], dtype='object')
Columns of data after make_features: Index(['AAPL Close', 'AAPL ret_t-0', 'AAPL ret_t-1', 'AAPL ret_t-2',
       'AAPL ret_t-3', 'AAPL ret_t-4', 'AAPL ret_t-5', 'AAPL ret_t-6',
       'AAPL ret_t-7', 'AAPL ret_t-8', 'AAPL ret_t-9', 'AAPL ret_t-10',
       'AAPL ret_t-11', 'AAPL ret_t-12', 'AAPL ret_t-13', 'AAPL ret_t-14',
       'AAPL ret_t-15', 'AAPL ret_t-16', 'AAPL ret_t-17', 'AAPL ret_t-18',
       'AAPL ret_t-19', 'AAPL sma_5', 'AAPL sma_10', 'AAPL sma_20',
       'AAPL rsi_14', 'AAPL macd', 'AAPL macd_signal', 'AAPL macd_hist',
       'AAPL vol_10'],
      dtype='object')
feature_names = ['AAPL ret_t-0', 'AAPL ret_t-1', 'AAPL ret_t-2', 'AAPL ret_t-3', 'AAPL ret_t-4', 'AAPL ret_t-5', 'AAPL ret_t-6', 'AAPL ret_t-7', 'AAPL ret_t-8', 'AAPL ret_t-9', 'AAPL ret_t-10', 'AAPL ret_t-11', 'AAPL ret_t-12', 'AAPL ret_t-13', 'AAPL ret_t-14', 'AAPL ret_t-15', 'AAPL ret_t-16', 'AAPL ret_t-17', 'AAPL ret_t-18', 'AAPL ret_t-19', 'AAPL sma_5', 'AAPL sma_10', 'AAPL sma_20', 'AAPL rsi_14', 'AAPL macd', 'AAPL macd_signal', 'AAPL macd_hist', 'AAPL vol_10']

,AAPL Close,AAPL ret_t-0,AAPL ret_t-1,AAPL ret_t-2,AAPL ret_t-3,AAPL ret_t-4,AAPL ret_t-5,AAPL ret_t-6,AAPL ret_t-7,AAPL ret_t-8,...,AAPL ret_t-18,AAPL ret_t-19,AAPL sma_5,AAPL sma_10,AAPL sma_20,AAPL rsi_14,AAPL macd,AAPL macd_signal,AAPL macd_hist,AAPL vol_10
0,29.8557,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,29.8357,-0.000670,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN
2,29.9043,0.002299,-0.000670,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,-0.000053,0.000000,-0.000053,NaN
3,30.1014,0.006591,0.002299,-0.000670,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000088,-0.000011,0.000099,NaN
4,31.2786,0.039108,0.006591,0.002299,-0.000670,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000720,0.000009,0.000710,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2513,298.1800,-0.047500,-0.022635,-0.010259,0.014483,-0.018311,0.000246,-0.007121,0.023748,-0.006033,...,0.028289,-0.029405,0.022789,0.026731,0.020767,0.061910,0.012653,0.019633,-0.006980,0.014730
2514,288.0800,-0.033872,-0.047500,-0.022635,-0.010259,0.014483,-0.018311,0.000246,-0.007121,0.023748,...,0.020932,0.028289,0.055839,0.070605,0.068296,-0.147191,0.006479,0.019146,-0.012668,0.020060
2515,292.6500,0.015864,-0.033872,-0.047500,-0.022635,-0.010259,0.014483,-0.018311,0.000246,-0.007121,...,-0.001449,0.020932,0.071390,0.096522,0.102128,-0.432710,-0.001686,0.017195,-0.018881,0.021258
2516,273.5200,-0.065368,0.015864,-0.033872,-0.047500,-0.022635,-0.010259,0.014483,-0.018311,0.000246,...,-0.044339,-0.001449,0.033494,0.070186,0.080639,-0.394089,-0.006867,0.013209,-0.020076,0.022862
2517,273.3600,-0.000585,-0.065368,0.015864,-0.033872,-0.047500,-0.022635,-0.010259,0.014483,-0.018311,...,-0.002746,-0.044339,0.071571,0.125409,0.146929,-0.584398,-0.017208,0.009837,-0.027045,0.026029

In [19]:
# Make sure all the NaNs are in the first rows and delete these rows
def remove_nans(data: pd.DataFrame) -> pd.DataFrame:
    print("Number of NaNs in each column:\n", data.isna().sum(axis=0))
    max_nans_per_col = data.isna().sum(axis=0).max()
    print("max_nans_per_col = %d" % max_nans_per_col)
    data = data.loc[max_nans_per_col:]
    data.reset_index(drop=True, inplace=True)
    nans_remaining = data.isna().sum().sum()
    print(f"Remaining NaNs after removing the {max_nans_per_col} first rows: {nans_remaining}")
    print(f"Shape: {data.shape}")
    return data

data = remove_nans(data)

Number of NaNs in each column:
 AAPL Close           0
AAPL ret_t-0         1
AAPL ret_t-1         2
AAPL ret_t-2         3
AAPL ret_t-3         4
AAPL ret_t-4         5
AAPL ret_t-5         6
AAPL ret_t-6         7
AAPL ret_t-7         8
AAPL ret_t-8         9
AAPL ret_t-9        10
AAPL ret_t-10       11
AAPL ret_t-11       12
AAPL ret_t-12       13
AAPL ret_t-13       14
AAPL ret_t-14       15
AAPL ret_t-15       16
AAPL ret_t-16       17
AAPL ret_t-17       18
AAPL ret_t-18       19
AAPL ret_t-19       20
AAPL sma_5           5
AAPL sma_10         10
AAPL sma_20         20
AAPL rsi_14         15
AAPL macd            1
AAPL macd_signal     2
AAPL macd_hist       2
AAPL vol_10         11
dtype: int64
max_nans_per_col = 20
Remaining NaNs after removing the 20 first rows: 0
Shape: (2498, 29)

In [20]:
# For each column, check the mean, std, min, max of the features
data.describe()

,AAPL Close,AAPL ret_t-0,AAPL ret_t-1,AAPL ret_t-2,AAPL ret_t-3,AAPL ret_t-4,AAPL ret_t-5,AAPL ret_t-6,AAPL ret_t-7,AAPL ret_t-8,...,AAPL ret_t-18,AAPL ret_t-19,AAPL sma_5,AAPL sma_10,AAPL sma_20,AAPL rsi_14,AAPL macd,AAPL macd_signal,AAPL macd_hist,AAPL vol_10
count,2498.000000,2498.000000,2498.000000,2498.000000,2498.000000,2498.000000,2498.000000,2498.000000,2498.000000,2498.000000,...,2498.000000,2498.000000,2498.000000,2498.000000,2498.000000,2498.000000,2498.000000,2498.000000,2498.000000,2498.000000
mean,115.434770,0.000980,0.000988,0.001009,0.001005,0.001024,0.001048,0.001053,0.001058,0.001051,...,0.001067,0.001068,-0.001466,-0.003394,-0.007341,0.124097,0.005435,0.005418,0.000016,0.014744
std,60.445469,0.016296,0.016300,0.016247,0.016245,0.016233,0.016205,0.016200,0.016198,0.016196,...,0.016190,0.016190,0.018038,0.027495,0.040029,0.360362,0.018729,0.017736,0.006653,0.006830
min,33.198600,-0.123550,-0.123550,-0.123550,-0.123550,-0.123550,-0.123550,-0.123550,-0.123550,-0.123550,...,-0.123550,-0.123550,-0.060665,-0.090204,-0.101779,-0.835744,-0.071361,-0.064481,-0.027045,0.003330
25%,69.148225,-0.006925,-0.006925,-0.006925,-0.006925,-0.006922,-0.006917,-0.006917,-0.006904,-0.006904,...,-0.006878,-0.006878,-0.012488,-0.021586,-0.034594,-0.142101,-0.003821,-0.003577,-0.003978,0.009846
50%,101.705000,0.000860,0.000876,0.000876,0.000876,0.000887,0.000889,0.000889,0.000892,0.000889,...,0.000895,0.000895,-0.002633,-0.005737,-0.011630,0.125498,0.007301,0.007270,0.000184,0.013511
75%,155.315000,0.009766,0.009790,0.009790,0.009766,0.009790,0.009812,0.009812,0.009812,0.009790,...,0.009766,0.009766,0.007989,0.011811,0.014657,0.392462,0.018203,0.017007,0.004255,0.018108
max,327.200000,0.088741,0.088741,0.088741,0.088741,0.088741,0.088741,0.088741,0.088741,0.088741,...,0.088741,0.088741,0.097428,0.125409,0.158345,0.949766,0.048822,0.046175,0.020998,0.046262

## Observations
* For AAPL, seems like returns can be multiplied by 10, because std ≃ 0.015 and min/max ≃ +-0.1
* SMAs by 10 for similar reason
* MACD by 20
* RSI is already in [-1, +1]
* Vol can be almost 100*'d, maybe a bit less because max is 0.04.

In [21]:
def normalize(data: pd.DataFrame) -> pd.DataFrame:
    # Returns
    ret_cols = [col for col in data.columns if "ret_t" in col]
    print("Normalize returns:", ret_cols)
    for col in ret_cols:
        data.loc[:,col] *= 10
    
        
    # SMAs
    sma_cols = [col for col in data.columns if "sma_" in col]
    print("Normalize sma:", sma_cols)
    for col in sma_cols:
        data.loc[:,col] *= 10
        
    # MACD
    macd_cols = [col for col in data.columns if "macd" in col]
    print("Normalize macd:", macd_cols)
    for col in macd_cols:
        data.loc[:,col] *= 20
    
    # VOL
    vol_cols = [col for col in data.columns if "vol_" in col]
    print("Normalize vol:", vol_cols)
    for col in vol_cols:
        data.loc[:,col] *= 40
        
    # Close
    close_cols = [col for col in data.columns if "Close" in col]
    print("Normalize close:", close_cols)
    for col in close_cols:
        data.loc[:,col] /= data.loc[0, col] 
        
    return data

data = normalize(data)
data.describe()

Normalize returns: ['AAPL ret_t-0', 'AAPL ret_t-1', 'AAPL ret_t-2', 'AAPL ret_t-3', 'AAPL ret_t-4', 'AAPL ret_t-5', 'AAPL ret_t-6', 'AAPL ret_t-7', 'AAPL ret_t-8', 'AAPL ret_t-9', 'AAPL ret_t-10', 'AAPL ret_t-11', 'AAPL ret_t-12', 'AAPL ret_t-13', 'AAPL ret_t-14', 'AAPL ret_t-15', 'AAPL ret_t-16', 'AAPL ret_t-17', 'AAPL ret_t-18', 'AAPL ret_t-19']
Normalize sma: ['AAPL sma_5', 'AAPL sma_10', 'AAPL sma_20']
Normalize macd: ['AAPL macd', 'AAPL macd_signal', 'AAPL macd_hist']
Normalize vol: ['AAPL vol_10']
Normalize close: ['AAPL Close']

,AAPL Close,AAPL ret_t-0,AAPL ret_t-1,AAPL ret_t-2,AAPL ret_t-3,AAPL ret_t-4,AAPL ret_t-5,AAPL ret_t-6,AAPL ret_t-7,AAPL ret_t-8,...,AAPL ret_t-18,AAPL ret_t-19,AAPL sma_5,AAPL sma_10,AAPL sma_20,AAPL rsi_14,AAPL macd,AAPL macd_signal,AAPL macd_hist,AAPL vol_10
count,2498.000000,2498.000000,2498.000000,2498.000000,2498.000000,2498.000000,2498.000000,2498.000000,2498.000000,2498.000000,...,2498.000000,2498.000000,2498.000000,2498.000000,2498.000000,2498.000000,2498.000000,2498.000000,2498.000000,2498.000000
mean,3.477098,0.009799,0.009877,0.010091,0.010045,0.010245,0.010480,0.010528,0.010579,0.010515,...,0.010670,0.010679,-0.014656,-0.033943,-0.073410,0.124097,0.108692,0.108364,0.000328,0.589762
std,1.820723,0.162957,0.162995,0.162473,0.162448,0.162326,0.162048,0.161995,0.161980,0.161958,...,0.161899,0.161897,0.180379,0.274955,0.400287,0.360362,0.374579,0.354716,0.133057,0.273198
min,1.000000,-1.235501,-1.235501,-1.235501,-1.235501,-1.235501,-1.235501,-1.235501,-1.235501,-1.235501,...,-1.235501,-1.235501,-0.606645,-0.902038,-1.017786,-0.835744,-1.427223,-1.289613,-0.540906,0.133214
25%,2.082866,-0.069249,-0.069249,-0.069249,-0.069249,-0.069223,-0.069172,-0.069172,-0.069036,-0.069036,...,-0.068777,-0.068777,-0.124875,-0.215863,-0.345935,-0.142101,-0.076428,-0.071536,-0.079563,0.393834
50%,3.063533,0.008600,0.008755,0.008755,0.008755,0.008871,0.008894,0.008894,0.008921,0.008894,...,0.008953,0.008953,-0.026332,-0.057367,-0.116301,0.125498,0.146016,0.145397,0.003671,0.540439
75%,4.678360,0.097660,0.097898,0.097898,0.097660,0.097898,0.098118,0.098118,0.098118,0.097898,...,0.097660,0.097660,0.079895,0.118106,0.146571,0.392462,0.364059,0.340150,0.085103,0.724329
max,9.855837,0.887406,0.887406,0.887406,0.887406,0.887406,0.887406,0.887406,0.887406,0.887406,...,0.887406,0.887406,0.974276,1.254095,1.583452,0.949766,0.976438,0.923506,0.419954,1.850485

## Do the same for Ford stock (F)

In [26]:
import os
import pandas as pd
import sys
# not great because assumes this is run from the location of the notebook, but no easy workaround
parent_dir = os.path.abspath(os.path.join(os.getcwd(), ".."))
if parent_dir not in sys.path:
    sys.path.append(parent_dir)
from data import make_features, load_and_clean_aapl_stock_data, get_ford_data_with_features, remove_nans

ford_data, _ = get_ford_data_with_features()
ford_data = remove_nans(ford_data)
ford_data

Columns of data after selecting Close and renaming it: Index(['F Close'], dtype='object', name='Price')
Columns of data after make_features: Index(['F Close', 'F ret_t-0', 'F ret_t-1', 'F ret_t-2', 'F ret_t-3',
       'F ret_t-4', 'F ret_t-5', 'F ret_t-6', 'F ret_t-7', 'F ret_t-8',
       'F ret_t-9', 'F ret_t-10', 'F ret_t-11', 'F ret_t-12', 'F ret_t-13',
       'F ret_t-14', 'F ret_t-15', 'F ret_t-16', 'F ret_t-17', 'F ret_t-18',
       'F ret_t-19', 'F sma_5', 'F sma_10', 'F sma_20', 'F rsi_14', 'F macd',
       'F macd_signal', 'F macd_hist', 'F vol_10'],
      dtype='object', name='Price')
feature_names = ['F ret_t-0', 'F ret_t-1', 'F ret_t-2', 'F ret_t-3', 'F ret_t-4', 'F ret_t-5', 'F ret_t-6', 'F ret_t-7', 'F ret_t-8', 'F ret_t-9', 'F ret_t-10', 'F ret_t-11', 'F ret_t-12', 'F ret_t-13', 'F ret_t-14', 'F ret_t-15', 'F ret_t-16', 'F ret_t-17', 'F ret_t-18', 'F ret_t-19', 'F sma_5', 'F sma_10', 'F sma_20', 'F rsi_14', 'F macd', 'F macd_signal', 'F macd_hist', 'F vol_10']
Number of NaNs in each column:
 Price
F Close           0
F ret_t-0         1
F ret_t-1         2
F ret_t-2         3
F ret_t-3         4
F ret_t-4         5
F ret_t-5         6
F ret_t-6         7
F ret_t-7         8
F ret_t-8         9
F ret_t-9        10
F ret_t-10       11
F ret_t-11       12
F ret_t-12       13
F ret_t-13       14
F ret_t-14       15
F ret_t-15       16
F ret_t-16       17
F ret_t-17       18
F ret_t-18       19
F ret_t-19       20
F sma_5           5
F sma_10         10
F sma_20         20
F rsi_14         15
F macd            1
F macd_signal     2
F macd_hist       2
F vol_10         11
dtype: int64
max_nans_per_col = 20
Remaining NaNs after removing the 20 first rows: 0
Shape: (1489, 29)

Price,F Close,F ret_t-0,F ret_t-1,F ret_t-2,F ret_t-3,F ret_t-4,F ret_t-5,F ret_t-6,F ret_t-7,F ret_t-8,...,F ret_t-18,F ret_t-19,F sma_5,F sma_10,F sma_20,F rsi_14,F macd,F macd_signal,F macd_hist,F vol_10
0,7.630633,-0.008138,-0.005396,-0.021988,0.006914,-0.039834,0.007525,-0.004992,0.001666,-0.005799,...,0.017242,0.007899,0.023550,0.043261,0.096753,-0.691414,-0.029792,-0.014076,-0.015717,0.024235
1,7.595852,-0.004558,-0.008138,-0.005396,-0.021988,0.006914,-0.039834,0.007525,-0.004992,0.001666,...,0.016949,0.017242,0.017537,0.043459,0.099435,-0.696484,-0.032783,-0.017360,-0.015423,0.014094
2,7.449780,-0.019230,-0.004558,-0.008138,-0.005396,-0.021988,0.006914,-0.039834,0.007525,-0.004992,...,-0.003788,0.016949,0.015385,0.040362,0.097449,-0.791258,-0.035085,-0.020538,-0.014546,0.014125
3,7.122851,-0.043884,-0.019230,-0.004558,-0.008138,-0.005396,-0.021988,0.006914,-0.039834,0.007525,...,-0.005323,-0.003788,0.022969,0.051409,0.109826,-0.855857,-0.038648,-0.023907,-0.014740,0.014581
4,7.484557,0.050781,-0.043884,-0.019230,-0.004558,-0.008138,-0.005396,-0.021988,0.006914,-0.039834,...,-0.003823,-0.005323,0.052734,0.085106,0.147861,-0.872819,-0.045978,-0.028088,-0.017890,0.017723
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1484,11.176902,0.000810,0.045763,-0.018303,0.007544,-0.007487,-0.004967,0.074733,0.007169,0.008130,...,0.002901,-0.005769,-0.025770,-0.054538,-0.100405,0.651852,0.032947,0.018018,0.014930,0.027425
1485,11.267404,0.008097,0.000810,0.045763,-0.018303,0.007544,-0.007487,-0.004967,0.074733,0.007169,...,0.021215,0.002901,-0.021215,-0.044453,-0.093239,0.637066,0.035334,0.020987,0.014348,0.027663
1486,11.213102,-0.004819,0.008097,0.000810,0.045763,-0.018303,0.007544,-0.007487,-0.004967,0.074733,...,-0.031162,0.021215,-0.020723,-0.041044,-0.092048,0.714285,0.037168,0.023665,0.013503,0.027608
1487,11.167851,-0.004036,-0.004819,0.008097,0.000810,0.045763,-0.018303,0.007544,-0.007487,-0.004967,...,0.031189,-0.031162,-0.010008,-0.026473,-0.079500,0.664062,0.038203,0.026493,0.011710,0.028116
1488,11.032099,-0.012156,-0.004036,-0.004819,0.008097,0.000810,0.045763,-0.018303,0.007544,-0.007487,...,0.011342,0.031189,0.002755,-0.013614,-0.068679,0.612902,0.038270,0.028952,0.009318,0.028500

In [27]:
ford_data.describe(percentiles=[0.1, 0.9])

Price,F Close,F ret_t-0,F ret_t-1,F ret_t-2,F ret_t-3,F ret_t-4,F ret_t-5,F ret_t-6,F ret_t-7,F ret_t-8,...,F ret_t-18,F ret_t-19,F sma_5,F sma_10,F sma_20,F rsi_14,F macd,F macd_signal,F macd_hist,F vol_10
count,1489.000000,1489.000000,1489.000000,1489.000000,1489.000000,1489.000000,1489.000000,1489.000000,1489.000000,1489.000000,...,1489.000000,1489.000000,1489.000000,1489.000000,1489.000000,1489.000000,1489.000000,1489.000000,1489.000000,1489.000000
mean,8.984360,0.000576,0.000580,0.000568,0.000576,0.000544,0.000548,0.000514,0.000528,0.000519,...,0.000408,0.000406,0.000209,0.000541,0.001821,0.002065,-0.002022,-0.002235,0.000212,0.022948
std,2.905184,0.025910,0.025908,0.025915,0.025915,0.025935,0.025936,0.025910,0.025905,0.025905,...,0.025900,0.025899,0.028833,0.044540,0.069428,0.350756,0.033677,0.032095,0.011626,0.011989
min,3.164625,-0.123242,-0.123242,-0.123242,-0.123242,-0.123242,-0.123242,-0.123242,-0.123242,-0.123242,...,-0.123242,-0.123242,-0.141002,-0.169619,-0.237583,-0.875556,-0.239470,-0.190461,-0.049010,0.004767
10%,5.617404,-0.027101,-0.027101,-0.027101,-0.027101,-0.027189,-0.027189,-0.027189,-0.027189,-0.027189,...,-0.027221,-0.027221,-0.031971,-0.049592,-0.077696,-0.467078,-0.042525,-0.038778,-0.013155,0.010956
50%,8.473184,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,-0.000165,-0.001076,-0.000141,-0.002801,0.000778,0.000908,0.000010,0.020547
90%,12.536014,0.028259,0.028259,0.028259,0.028259,0.028259,0.028259,0.028087,0.028087,0.028087,...,0.028026,0.028026,0.032050,0.047292,0.075321,0.486870,0.037395,0.036007,0.014478,0.038108
max,19.979622,0.234414,0.234414,0.234414,0.234414,0.234414,0.234414,0.234414,0.234414,0.234414,...,0.234414,0.234414,0.143556,0.262000,0.486533,0.787097,0.073997,0.061932,0.042972,0.107023

In [28]:
def ford_normalize(data: pd.DataFrame) -> pd.DataFrame:
    # Returns
    ret_cols = [col for col in data.columns if "ret_t" in col]
    print("Normalize returns:", ret_cols)
    for col in ret_cols:
        data.loc[:,col] *= 20
    
        
    # SMAs
    sma_cols = [col for col in data.columns if "sma_" in col]
    print("Normalize sma:", sma_cols)
    for col in sma_cols:
        data.loc[:,col] *= 10
        
    # MACD
    macd_cols = [col for col in data.columns if "macd" in col]
    print("Normalize macd:", macd_cols)
    for col in macd_cols:
        data.loc[:,col] *= 20
    
    # VOL
    vol_cols = [col for col in data.columns if "vol_" in col]
    print("Normalize vol:", vol_cols)
    for col in vol_cols:
        data.loc[:,col] *= 40
        
    # Close
    close_cols = [col for col in data.columns if "Close" in col]
    print("Normalize close:", close_cols)
    for col in close_cols:
        data.loc[:,col] /= data.loc[0, col] 
    
    return data

ford_data = ford_normalize(ford_data)

Normalize returns: ['F ret_t-0', 'F ret_t-1', 'F ret_t-2', 'F ret_t-3', 'F ret_t-4', 'F ret_t-5', 'F ret_t-6', 'F ret_t-7', 'F ret_t-8', 'F ret_t-9', 'F ret_t-10', 'F ret_t-11', 'F ret_t-12', 'F ret_t-13', 'F ret_t-14', 'F ret_t-15', 'F ret_t-16', 'F ret_t-17', 'F ret_t-18', 'F ret_t-19']
Normalize sma: ['F sma_5', 'F sma_10', 'F sma_20']
Normalize macd: ['F macd', 'F macd_signal', 'F macd_hist']
Normalize vol: ['F vol_10']
Normalize close: ['F Close']

In [29]:
ford_data.describe(percentiles=[0.1, 0.9])

Price,F Close,F ret_t-0,F ret_t-1,F ret_t-2,F ret_t-3,F ret_t-4,F ret_t-5,F ret_t-6,F ret_t-7,F ret_t-8,...,F ret_t-18,F ret_t-19,F sma_5,F sma_10,F sma_20,F rsi_14,F macd,F macd_signal,F macd_hist,F vol_10
count,1489.000000,1489.000000,1489.000000,1489.000000,1489.000000,1489.000000,1489.000000,1489.000000,1489.000000,1489.000000,...,1489.000000,1489.000000,1489.000000,1489.000000,1489.000000,1489.000000,1489.000000,1489.000000,1489.000000,1489.000000
mean,1.177407,0.011516,0.011607,0.011365,0.011523,0.010879,0.010969,0.010288,0.010556,0.010377,...,0.008168,0.008122,0.002091,0.005409,0.018205,0.002065,-0.040449,-0.044690,0.004241,0.917903
std,0.380726,0.518200,0.518167,0.518293,0.518296,0.518704,0.518717,0.518195,0.518103,0.518101,...,0.517998,0.517981,0.288334,0.445403,0.694277,0.350756,0.673537,0.641900,0.232523,0.479545
min,0.414726,-2.464836,-2.464836,-2.464836,-2.464836,-2.464836,-2.464836,-2.464836,-2.464836,-2.464836,...,-2.464836,-2.464836,-1.410019,-1.696185,-2.375830,-0.875556,-4.789408,-3.809215,-0.980192,0.190673
10%,0.736165,-0.542023,-0.542023,-0.542023,-0.542023,-0.543774,-0.543774,-0.543774,-0.543774,-0.543774,...,-0.544430,-0.544430,-0.319712,-0.495920,-0.776956,-0.467078,-0.850493,-0.775559,-0.263107,0.438221
50%,1.110417,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,-0.001654,-0.010761,-0.001414,-0.002801,0.015551,0.018155,0.000202,0.821884
90%,1.642854,0.565174,0.565174,0.565174,0.565174,0.565174,0.565174,0.561732,0.561732,0.561732,...,0.560516,0.560516,0.320499,0.472922,0.753214,0.486870,0.747902,0.720134,0.289566,1.524335
max,2.618344,4.688272,4.688272,4.688272,4.688272,4.688272,4.688272,4.688272,4.688272,4.688272,...,4.688272,4.688272,1.435561,2.620001,4.865334,0.787097,1.479931,1.238638,0.859446,4.280930